// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    label: '_3BPD3zRzS0aET_ptOoUgZj',
} as const;

export type ClassName = string;

export default styles;