// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    appNav: '_2lAduzCawBZbLxuHLbkplA',
    open: '_3rE-tMb69cbeV4EQxiBr8j',
    appNavExit: '_2OwIz6PIhHb21BfoWzeuac',
    appNavExitActive: '_3l4tQ2PmtaM7byPtwtIu-H',
    appNavEnter: 'nA6z1G2WHjP1X_NHAGE98',
    appNavEnterActive: '_158p1JxxhrEgSSOiscd5Jn',
    caller: 'OCTvrnUjOUc_8r8JoCgJ0',
    appMenu: 't68DDac_LlbLxq-yezoD4',
    item: '_2F7n1rsYNTD7IbGsPLYpqx',
} as const;

export type ClassName = string;

export default styles;