// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    navigation: '_3JepMlm7k3SnHChy46qeLw',
    item: 'dMyFape7j9vMvOVl7uOZ',
    link: '_14-ryoHqLu_VUAwRCYjPNq',
    active: '_1DFSSJmNC6r2jDMa3svspK',
    horizontal: 'A2ybV-yTGOd2zCqVlHbjV',
} as const;

export type ClassName = string;

export default styles;