name: Publish Dhampir Core

on:
    push:
        branches:
            - 'feature/**'
            - 'fix/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Build
                run: |
                    yarn install
                    yarn build:dist
                working-directory: packages/core
    publish:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
                    registry-url: https://npm.pkg.github.com/
            -   name: Publish
                run: |
                    npm publish
                env:
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
