name: Publish Dhampir Core

on:
    push:
        branches:
            - 'develop'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: "[Core] Install Packages"
                uses: borales/actions-yarn@v4
                with:
                    cmd: install --immutable
                    dir: packages/core

            -   name: "[Core] Build Library"
                uses: borales/actions-yarn@v4
                with:
                    cmd: build:dist
                    dir: packages/core

            -   name: "[Core] Test"
                uses: borales/actions-yarn@v4
                with:
                    cmd: test:unit
                    dir: packages/core
    publish:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
                    registry-url: https://npm.pkg.github.com/
                    scope: '@dhampirjs'
            -   name: "[Core] Install"
                run: ls -la
                working-directory: ./packages/core

            -   name: "[Core] Install"
                uses: borales/actions-yarn@v4
                with:
                    cmd: install --immutable
                    dir: packages/core

            -   name: "[Core] Build Distributive Files"
                uses: borales/actions-yarn@v4
                with:
                    cmd: build:dist
                    dir: packages/core

            -   name: "[Core] Publish Preview Package"
                run: npm publish
                working-directory: ./packages/core
                env:
                    NODE_AUTH_TOKEN: ${{secrets.NODE_PUBLISH}}
